# Generated by Django 4.2.1 on 2024-04-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0003_alter_menu_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='path',
            field=models.URLField(default='parent/', verbose_name='Путь'),
            preserve_default=False,
        ),
    ]
