# Generated by Django 4.2.1 on 2024-04-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0004_menu_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='root',
            field=models.CharField(max_length=255, verbose_name='Корень/название меню'),
        ),
    ]
